[workspace.package]
version = "0.8.0"
edition = "2024"
authors = ["Tweag"]
homepage = "https://topiary.tweag.io"
repository = "https://github.com/topiary/topiary"
documentation = "https://topiary.tweag.io/book"
readme = "README.md"
license = "MIT"

[workspace]
members = [
  "topiary-core",
  "topiary-cli",
  "topiary-queries",
  "topiary-config",
  "topiary-web-tree-sitter-sys",
  "topiary-tree-sitter-facade",
  "examples/*",
]
default-members = ["topiary-core", "topiary-cli"]
resolver = "2"

[profile.release]
lto = true
opt-level = 's'
# https://docs.rs/rootcause-backtrace/latest/rootcause_backtrace/#debugging-symbols-in-release-builds
strip = false
debug = 1

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace.dependencies]
anyhow = "1.0"
assert_cmd = "2.2"
async-scoped = { version = "0.9.0", features = ["use-tokio"] }
clap = { version = "4.6", features = ["env", "derive"] }
clap_complete = "4.6"
clap_derive = "4.6"
criterion = "0.8"
directories = "6.0"
env_logger = "0.11"
gix = { version = "0.88.0", features = ["blocking-http-transport-reqwest-rust-tls"] }
js-sys = "0.3"
libloading = "0.9.0"
log = "0.4"
miette = "7.6.0"
nickel-lang-core = { version = "0.19.0", default-features = false }
pastey = "0.2.3"
predicates = "3.1"
pretty_assertions = "1.4"
prettydiff = { version = "0.9.0", default-features = false }
rayon = "1.12"
rootcause = "0.13"
rootcause-preformat = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
streaming-iterator = "0.1.9"
tabled = { version = "0.22.0", default-features = false, features = ["std"] }
tempfile = "3.27"
test-log = "0.2"
thiserror = "2.0.21"
tokio = "1.53"
tokio-test = "0.4"
toml = "1.1"
tree-sitter-language = "0.1"
unescape = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"
web-sys = "0.3"

# NOTE Keep these versions aligned
tree-sitter = "=0.27.0"         # NOTE Update tree-sitter-loader to match
tree-sitter-loader = "=0.27.0"  # NOTE Align with tree-sitter

# NOTE Update these appropriately
topiary-config = { version = "0.8.0", path = "./topiary-config" }
topiary-core = { version = "0.8.0", path = "./topiary-core" }
topiary-queries = { version = "0.8.0", path = "./topiary-queries" }
topiary-tree-sitter-facade = { version = "0.8.0", path = "./topiary-tree-sitter-facade" }
topiary-web-tree-sitter-sys = { version = "0.8.0", path = "./topiary-web-tree-sitter-sys" }
similar = "3.2"
rootcause-backtrace = "0.13.0"

[profile.dev.package.lalrpop]
opt-level = 3

[profile.release.package.lalrpop]
opt-level = 3

[workspace.metadata.typos]
files.extend-exclude = [
  "/topiary-cli/tests/samples",
]
